# Numpy

- NumPy (Numerical Python) gives you the ndarray — a fixed-type, packed array built for fast math.
- When you multiply two NumPy arrays, it runs compiled C code under the hood. That makes it 10–100x faster than doing the same math in a Python loop.
- all elements in a NumPy array must be the same type — usually int64 or float64

- NumPy is also the backbone of nearly everything in the Python data/AI world — pandas, scikit-learn, TensorFlow all use it internally.




In [ ]:
# Import
import numpy as np



#### Common Functions


In [ ]:
# np.array() wraps an existing Python list into a NumPy array.
a = np.array([1, 2, 3, 4])

# .ndim tells the number of dimensions (axes) of the array
print(a.ndim)

# .shape tells the dimensions (axes) of the array
print(a.shape) 
# For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim


# the total number of elements of the array. This is equal to the product of the elements of shape
print(a.size)

# dtype tells the type of elements in the array
# numpy can auto choose this or you can specify when creating using dtype=float
#
#  One can create or specify dtype’s using standard Python types. 
# Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 etc
print(a.dtype)

# itemsize the size in bytes of each element of the array.
print(a.itemsize) # equivalent to ndarray.dtype.itemsize.


1
(4,)
4
int64
8


#### Creating ndarrays

np.array() wraps an existing Python list into a numpy array
.shape

In [3]:
# from list

a = np.array([1, 2, 3, 4])
# dtype is inferred → int64

b = np.array([1.0, 2.5, 3.7])
# dtype → float64

# 2D array (matrix)
m = np.array([[1,2],[3,4]])

print(type(m))

<class 'numpy.ndarray'>


In [1]:
# Pre-filled arrays
# The function zeros creates an array full of zeros, the function ones creates an array full of ones, 
# and the function empty creates an array whose initial content is random

np.zeros(5)
# [0. 0. 0. 0. 0.]

np.ones((2, 3))
# [[1. 1. 1.]
#  [1. 1. 1.]]

np.full((3,), 7)
# [7 7 7]

print(np.empty([2, 2]))


NameError: name 'np' is not defined